### ISSUE TITLE
Display Labels for Sheet Music Collections

### ISSUE THREAD

**Issue by Favenzio** [FLVC/islandoratheme#32] opened 2015-01-21 17:16 UTC
Krystal reports the following:

Two alt title fields have display labels they are supposed to be defaulting to and that’s not happening.

Also, the Instrumentation field is not combining multiple lines into a single field (like what we did with the Subject field). 

Here’s an object that is showing both problems: http://purl.flvc.org/fsu/fd/FSUML-CSMC-H3689 [Open URL]

-Favenzio.

**Comment by mdemers** [comment] 2015-01-21 17:26
Favenzio - I discussed these issues with Krystal and it looks they are both are correct according to spec. I told her we'd have to go through ISG first before changing them but the agenda of the last meeting was a bit full. I'll forward you our email thread.

**Comment by lydiam** [comment] 2015-01-22 14:52
Here’s what I see in the display specs in the Full MODS form document (https://docs.google.com/spreadsheets/d/1eywxce_wVw3Nfdy3hiOtgC_p8bZ_XKdkNtbMTM1XeBs/edit?usp=sharing):

Display label depending on TYPE: If value is null or no TYPE attrubute, label = "Title: ". Otherwise label = value of Type concat with "title: ", e.g., "Alternative title: "

This is what’s in the MODS, which :

<titleInfo type="alternative" displayLabel="Cover Title"><title>No Surrender</title>
<subTitle>Song</subTitle></titleInfo>

<titleInfo type="alternative" displayLabel="First Line">
<title>Ever constant, ever true</title></titleInfo>

Per the MODS standard:

displayLabel – This attribute provides additional text associated with the element if needed for display purposes.  The preferred text with its capitalization should be included, but not delimiters such as colons.

It’s a valid attribute of displayLabel.

So this is essentially a display enhancement request and not a bug report, in that we’ve never committed to using titileinfo @displayLabel.

**Comment by lydiam** [comment] 2015-01-22 16:46
My apologies.  I've confused this issue.  I will let Mike comment and indicate the status of this situation.  I will correct my comments yet again.

**Comment by lydiam** [comment] 2015-01-22 17:01
Mike will clarify whether Krystal is asking to change the spec to perhaps use the @displayLabel *instead of*  the label generated from @type.  If that's the case he'll ask ISG if this is a change that they want as well.

**Comment by Favenzio** [comment] 2015-02-05 21:34
Krystal reports that this issue was discussed at ISG this week. Lydia or Mike, could you guys update this ticket with the results of that discussion? Does anything need to change or can I go ahead and close this ticket?

**Comment by mdemers** [comment] 2015-02-05 21:49
There was still some confusion about it during ISG but no one has objected. I sent out the attached document over the FL-Islandora listserv to clarify and no one has given any feedback so far. You could probably use it as a spec to make the changes. Unless Lydia thinks we should sit on this longer for comments I think we should go ahead and make the changes.

**Comment by Favenzio** [comment] 2015-02-05 22:19
When you say "attached document" do you mean attached to the comment? I don't see it. I'm not in the FL-Islandora listserv so, if you could email it to me, I would appreciate it.

**Comment by mdemers** [comment] 2015-02-05 22:27
https://docs.google.com/document/d/1ybR1Hnaiwkb2TFNiFmLgAvfzHcSKZa731ZARIPcMVO4/edit?usp=sharing

**Comment by lydiam** [comment] 2015-03-30 18:29
Mike - I'm putting this on the 3/31/15 ISG agenda to make a final decision and move along with implementation.

**Comment by mdemers** [comment] 2015-04-02 18:44
Favenzio patched on dev. Ready for test.

**Comment by Favenzio** [comment] 2015-04-07 16:30
This patch has been pulled on test. Please test and let me know if it is ready for production.

**Comment by mdemers** [comment] 2015-04-07 20:37
Looks ready for production. Thanks

**Comment by lydiam** [comment] 2015-04-14 14:36
Is this in production yet?  If so I'd like to notify ISG.

**Comment by mdemers** [comment] 2015-04-15 20:09
Went into production with the other islandoratheme changes. Thanks Favenzio.

**Closed by mdemers** 2015-04-15 20:09 UTC
